### ISSUE TITLE
超强二笔30键配置方案中翻页键与字典词汇用键冲突

### ISSUE THREAD

**Issue by happypxw** [whjiang/cqeb_rime#2]
如题，主要是两个键：逗号（,）和句号（.）

**Comment by lanyun712** [comment]
收到，感谢反馈，正在处理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whjiang/cqeb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午4:49
收件人:&nbsp;"whjiang/cqeb"<cqeb@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[whjiang/cqeb] 超强二笔30键配置方案中翻页键与字典词汇用键冲突 (#2)





 
如题，主要是两个键：逗号（,）和句号（.）

**Comment by lanyun712** [comment]
已修复，目前已发到两笔QQ群493662737，这里等果贝大佬有空改

**Comment by happypxw** [comment]
好的 谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;lanyun712&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月17日(星期天) 晚上9:19
收件人:&nbsp;&quot;whjiang/cqeb&quot;<cqeb@noreply.github.com&gt;;
抄送:&nbsp;&quot;happypxw&quot;<happypxw@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [whjiang/cqeb] 超强二笔30键配置方案中翻页键与字典词汇用键冲突 (#2)

**Comment by whjiang** [comment]
> 收到，感谢反馈，正在处理
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "whjiang/cqeb" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月12日(星期二) 下午4:49 收件人:&nbsp;"whjiang/cqeb"<cqeb@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[whjiang/cqeb] 超强二笔30键配置方案中翻页键与字典词汇用键冲突 (#2) 如题，主要是两个键：逗号（,）和句号（.） — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@lanyun712 能帮忙提一个pull request吗？

**Comment by eren000** [comment]
在win10上，（,) 输入没有问题，都是(.)的输入好像有问题。
1.比如“功能”输入 "gjn."  ,是翻页，这个正常吗？
2.单字输入
皴	c.,.
戳	c.;
戳	c.;v   
第二码为“.” ，第三码为标点时好像都有问题。

第三码为字母时，输入 “c.j”显示 ”c.j“ ,如下图：
-------------------------------
![image](https://user-images.githubusercontent.com/5646528/107016224-a55f1180-67d8-11eb-8e5e-614cfa427b1f.png)
第三码为符号时， 输入”c.,“ 只显示 “c“ ,如下图：
-------------------------------
![image](https://user-images.githubusercontent.com/5646528/107016370-d4758300-67d8-11eb-8367-aefff0c128e1.png)

继续输入”v“，只显示 “cv“ ,如下图：
-------------------------------
![image](https://user-images.githubusercontent.com/5646528/107017536-371b4e80-67da-11eb-85b9-e97f22e85196.png)

**Comment by lanyun712** [comment]
这个问题前段时间已经修复了啊，你是用的以前的版本吧，更新试试



---原始邮件---
发件人: "Eren"<notifications@github.com&gt;
发送时间: 2021年2月5日(周五) 下午5:32
收件人: "whjiang/cqeb"<cqeb@noreply.github.com&gt;;
抄送: "lanyun712"<lanyun712@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [whjiang/cqeb]超强二笔30键配置方案中翻页键与字典词汇用键冲突 (#2)




 
在win10上，（,) 输入没有问题，都是(.)的输入好像有问题。
 1.比如“功能”输入 "gjn."  ,是翻页。
 2.单字输入
 皴c.,.
 戳c.;
 戳c.;v
 第二码为“.” ，第三码为标点时好像都有问题。

**Comment by eren000** [comment]
> 这个问题前段时间已经修复了啊，你是用的以前的版本吧，更新试试
> […](#)
> ---原始邮件--- 发件人: "Eren"<notifications@github.com&gt; 发送时间: 2021年2月5日(周五) 下午5:32 收件人: "whjiang/cqeb"<cqeb@noreply.github.com&gt;; 抄送: "lanyun712"<lanyun712@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题: Re: [whjiang/cqeb]超强二笔30键配置方案中翻页键与字典词汇用键冲突 (#2) 在win10上，（,) 输入没有问题，都是(.)的输入好像有问题。 1.比如“功能”输入 "gjn." ,是翻页。 2.单字输入 皴c.,. 戳c.; 戳c.;v 第二码为“.” ，第三码为标点时好像都有问题。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

更新后没有作用，我删掉配置，重新安装后好了
