### ISSUE TITLE
Mac上只有音形码出字

### ISSUE THREAD

**Issue by jasonjoo2010** [whjiang/cqeb_rime#6]
感谢提供二笔输入法的扩展！

今天安装后，似乎除了音形码另外三个均打不出字，请教下这个有碰到过类似的问题吗？仔细查了下依赖词库都在了

**Comment by lbzj** [comment]
没遇到问题 你说 输 编码错了，明显没搞清 超强快码、超强两笔、超强音形 三者之间的区别，详见这里https://lbzj.github.io/2021/08/25/difference/

**Comment by jasonjoo2010** [comment]
> 没遇到问题 你说 输 编码错了，明显没搞清 超强快码、超强两笔、超强音形 三者之间的区别，详见这里https://lbzj.github.io/2021/08/25/difference/

发完后意识到有这个问题，所以把那部分内容编辑掉了
所以只保留了这个打不出字的问题，我安装后似乎只有切音形码才有反应，其它打字是白框不输出，不知道有无其它人碰到这个问题，另外我是apple M1 芯片下的最新系统

**Comment by whjiang** [comment]
我的新电脑也是Apple M1，没遇到你说的问题。

**Comment by 1sandy** [comment]
"Mac上只有音形内出字 Mac上只有音形码出字"

这个问题，我也遇到了，在我的M2 MACBOOK AIR上，几天了，搞不定。

我怀疑过是

```
patch:
  schema_list:
    - {schema: cqkm} #超强快码
    - {schema: cqkm_cm} #超强快码(重码版)，重码版相比无重码版并没有增加更多的词，仅是调整了编码方式
    - {schema: cqkm_42} #超强快码(弛放版)，追加拼音引擎，四码以内单字优先，四码开外转为类双拼输入法
    - {schema: cqlb} #超强二笔
    - {schema: cqyx} #超强音形
```

是这段配制文件在复制过程中缩进、空格之类的问题，但似乎不是。

如果，这个问题在您的机器上无法复现，暂时难以解决。能不能退而求其次，给几个语句，能让我反安装/清理

```
curl -fsSL https://git.io/rime-install | bash

bash rime-install pinyin-simp whjiang/cqeb
```

这2个语句带来的系统变化？？以便我可以尝试别的方式/别的发布版。感谢~

因为，刚用上MAC，LINUX/UNIX都不会，那个rime-install脚本看不太懂……
